import type {Metadata} from "next";
import {Inter} from 'next/font/google';
import Header from '@/components/core/header'
import "./globals.css";
import React from "react";
const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: "tasker",
    // description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover"></meta>
        </head>
        <body className={`${inter.className} bg-[#fefefe]`}>
        <Header/>
        {children}
        </body>
        </html>
    );
}
